Retemplate rubocop-lts r3_2-even-v24

diff --git a/.github/workflows/heads.yml b/.github/workflows/heads.yml
--- a/.github/workflows/heads.yml
+++ b/.github/workflows/heads.yml
@@ -1,10 +1,16 @@
-name: Ruby HEAD Support
+name: Heads
+
+permissions:
+  contents: read
+
+env:
+  K_SOUP_COV_DO: false
 
 on:
   push:
     branches:
       - 'main'
-      - 'r*-even-v*'
+      - '*-stable'
     tags:
       - '!*' # Do not execute on tags
   pull_request:
@@ -16,43 +22,73 @@ on:
 # Cancels all previous workflow runs for the same branch that have not yet completed.
 concurrency:
   # The concurrency group contains the workflow name and the branch name.
-  group: ${{ github.workflow }}-${{ github.ref }}
+  group: "${{ github.workflow }}-${{ github.ref }}"
   cancel-in-progress: true
 
 jobs:
   test:
-    name: Ruby ${{ matrix.ruby }} ${{matrix.gemfile}} ${{ matrix.name_extra || '' }}
-    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
-      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
     if: "!contains(github.event.commits[0].message, '[ci skip]') && !contains(github.event.commits[0].message, '[skip ci]')"
-    strategy:
-      fail-fast: false
-      matrix:
-        experimental: [false]
-        rubygems:
-          - latest
-        bundler:
-          - latest
-        gemfile:
-          - vanilla
-        ruby:
-          - "ruby-head"
-#          # NOTE: jruby-head is still @ Ruby 3.1 compat
-#          - "jruby-head"
-#          # NOTE: truffleruby-head is still @ Ruby 3.1 compat
-#          - "truffleruby-head"
-
+    name: Specs ${{ matrix.ruby }}@${{ matrix.appraisal }}${{ matrix.name_extra || '' }}
     runs-on: ubuntu-latest
     continue-on-error: ${{ matrix.experimental || endsWith(matrix.ruby, 'head') }}
+    env: # $BUNDLE_GEMFILE must be set at job level, so it is set for all steps
+      BUNDLE_GEMFILE: ${{ github.workspace }}/Appraisal.root.gemfile
+    strategy:
+      fail-fast: true
+      matrix:
+        include:
+          # NOTE: Heads use default rubygems / bundler; their defaults are custom, unreleased, and from the future!
+          # ruby-head
+          - ruby: "ruby-head"
+            appraisal: "head"
+            exec_cmd: "kettle-test"
+            rubygems: default
+            bundler: default
+
+          # truffleruby-head
+          - ruby: "truffleruby-head"
+            appraisal: "head"
+            exec_cmd: "kettle-test"
+            rubygems: default
+            bundler: default
+
+          # jruby-head
+          - ruby: "jruby-head"
+            appraisal: "head"
+            exec_cmd: "kettle-test"
+            rubygems: default
+            bundler: default
+
     steps:
       - name: Checkout
-        uses: actions/checkout@v3
-      - name: Setup Ruby & Bundle
-        uses: ruby/setup-ruby@v1
+        if: ${{ !env.ACT || (! startsWith(matrix.ruby, 'jruby') && !startsWith(matrix.ruby, 'truffleruby')) }}
+        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
+        with:
+          persist-credentials: false
+
+      - name: Setup Ruby & RubyGems
+        if: ${{ !env.ACT || (! startsWith(matrix.ruby, 'jruby') && !startsWith(matrix.ruby, 'truffleruby')) }}
+        uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1.310.0
         with:
           ruby-version: ${{ matrix.ruby }}
           rubygems: ${{ matrix.rubygems }}
           bundler: ${{ matrix.bundler }}
           bundler-cache: true
-      - name: Run tests
-        run: bundle exec rake test
+
+      - name: "[Attempt 1] Appraisal for ${{ matrix.ruby }}@${{ matrix.appraisal }}"
+        id: bundleAppraisalAttempt1
+        if: ${{ !env.ACT || (! startsWith(matrix.ruby, 'jruby') && !startsWith(matrix.ruby, 'truffleruby')) }}
+        run: bundle exec appraisal ${{ matrix.appraisal }} install
+        # Continue to the next step on failure
+        continue-on-error: true
+
+      # Effectively an automatic retry of the previous step.
+      - name: "[Attempt 2] Appraisal for ${{ matrix.ruby }}@${{ matrix.appraisal }}"
+        id: bundleAppraisalAttempt2
+        # If bundleAppraisalAttempt1 failed, try again here; Otherwise skip.
+        if: ${{ steps.bundleAppraisalAttempt1.outcome == 'failure' && (!env.ACT || (! startsWith(matrix.ruby, 'jruby') && !startsWith(matrix.ruby, 'truffleruby'))) }}
+        run: bundle exec appraisal ${{ matrix.appraisal }} install
+
+      - name: Tests for ${{ matrix.ruby }} via ${{ matrix.exec_cmd }}
+        if: ${{ !env.ACT || (! startsWith(matrix.ruby, 'jruby') && !startsWith(matrix.ruby, 'truffleruby')) }}
+        run: bundle exec appraisal ${{ matrix.appraisal }} bundle exec ${{ matrix.exec_cmd }}
